import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase environment variables')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseKey)

const MOMBASA_PRICES = [
  {
    category: 'cement',
    material: 'Ordinary Portland Cement',
    description: 'Bamburi 32.5N — standard structural use',
    unit: '50kg bag',
    price_kes: 720,
    region: 'mombasa',
    supplier: 'Bamburi Cement',
    supplier_contact: '+254 41 222 1001',
  },
  {
    category: 'cement',
    material: 'Portland Pozzolana Cement',
    description: 'Bamburi Plus 32.5R — blended, coastal durability',
    unit: '50kg bag',
    price_kes: 700,
    region: 'mombasa',
    supplier: 'Bamburi Cement',
    supplier_contact: '+254 41 222 1001',
  },
  {
    category: 'cement',
    material: 'Sulphate Resistant Cement',
    description: 'For coastal foundations — resists salt water',
    unit: '50kg bag',
    price_kes: 850,
    region: 'mombasa',
    supplier: 'East African Portland',
    supplier_contact: '+254 722 205 202',
  },
  {
    category: 'steel',
    material: 'Y8 Deformed Bar',
    description: 'High yield reinforcement — stirrups, links',
    unit: 'kg',
    price_kes: 115,
    region: 'mombasa',
    supplier: 'Steel Masters Mombasa',
    supplier_contact: '+254 722 333 444',
  },
  {
    category: 'steel',
    material: 'Y10 Deformed Bar',
    description: 'High yield reinforcement — slabs, beams',
    unit: 'kg',
    price_kes: 115,
    region: 'mombasa',
    supplier: 'Steel Masters Mombasa',
    supplier_contact: '+254 722 333 444',
  },
  {
    category: 'steel',
    material: 'Y12 Deformed Bar',
    description: 'High yield reinforcement — columns, beams',
    unit: 'kg',
    price_kes: 112,
    region: 'mombasa',
    supplier: 'Steel Masters Mombasa',
    supplier_contact: '+254 722 333 444',
  },
  {
    category: 'steel',
    material: 'Y16 Deformed Bar',
    description: 'High yield reinforcement — main column bars',
    unit: 'kg',
    price_kes: 110,
    region: 'mombasa',
    supplier: 'Steel Masters Mombasa',
    supplier_contact: '+254 722 333 444',
  },
  {
    category: 'steel',
    material: 'Y20 Deformed Bar',
    description: 'Heavy structural — transfer beams, raft foundations',
    unit: 'kg',
    price_kes: 108,
    region: 'mombasa',
    supplier: 'Steel Masters Mombasa',
    supplier_contact: '+254 722 333 444',
  },
  {
    category: 'steel',
    material: 'BRC Mesh A142',
    description: 'Welded fabric — ground floor slabs',
    unit: 'm²',
    price_kes: 580,
    region: 'mombasa',
    supplier: 'Steel Masters Mombasa',
    supplier_contact: '+254 722 333 444',
  },
  {
    category: 'steel',
    material: 'Binding Wire',
    description: 'Gauge 16 annealed — tying reinforcement',
    unit: 'kg',
    price_kes: 180,
    region: 'mombasa',
    supplier: 'Coast Builders Centre',
    supplier_contact: '+254 41 231 0000',
  },
  {
    category: 'aggregates',
    material: 'River Sand',
    description: 'Washed river sand — plastering, masonry',
    unit: 'm³',
    price_kes: 2800,
    region: 'mombasa',
    supplier: 'Coast Aggregates Ltd',
    supplier_contact: '+254 722 500 600',
  },
  {
    category: 'aggregates',
    material: 'Ballast 20mm',
    description: 'Crushed stone — concrete mixes',
    unit: 'm³',
    price_kes: 3800,
    region: 'mombasa',
    supplier: 'Coast Aggregates Ltd',
    supplier_contact: '+254 722 500 600',
  },
  {
    category: 'aggregates',
    material: 'Ballast 40mm',
    description: 'Crushed stone — mass concrete, blinding',
    unit: 'm³',
    price_kes: 3500,
    region: 'mombasa',
    supplier: 'Coast Aggregates Ltd',
    supplier_contact: '+254 722 500 600',
  },
  {
    category: 'aggregates',
    material: 'Hardcore',
    description: 'Murram fill — sub-base under slabs',
    unit: 'm³',
    price_kes: 2200,
    region: 'mombasa',
    supplier: 'Coast Aggregates Ltd',
    supplier_contact: '+254 722 500 600',
  },
  {
    category: 'aggregates',
    material: 'Coral Sand',
    description: 'Coast-specific — block making, backfill',
    unit: 'm³',
    price_kes: 1800,
    region: 'mombasa',
    supplier: 'Local suppliers',
    supplier_contact: '',
  },
  {
    category: 'masonry',
    material: 'Hollow Block 150mm',
    description: '6 inch hollow concrete block — standard walling',
    unit: 'piece',
    price_kes: 65,
    region: 'mombasa',
    supplier: 'Mombasa Block Makers',
    supplier_contact: '+254 722 700 800',
  },
  {
    category: 'masonry',
    material: 'Hollow Block 200mm',
    description: '8 inch hollow concrete block — external walls',
    unit: 'piece',
    price_kes: 85,
    region: 'mombasa',
    supplier: 'Mombasa Block Makers',
    supplier_contact: '+254 722 700 800',
  },
  {
    category: 'masonry',
    material: 'Solid Block 150mm',
    description: 'Dense concrete block — retaining walls',
    unit: 'piece',
    price_kes: 75,
    region: 'mombasa',
    supplier: 'Mombasa Block Makers',
    supplier_contact: '+254 722 700 800',
  },
  {
    category: 'masonry',
    material: 'Coral Stone',
    description: 'Traditional coast material — feature walls',
    unit: 'piece',
    price_kes: 45,
    region: 'mombasa',
    supplier: 'Coast Stone Suppliers',
    supplier_contact: '+254 722 900 100',
  },
  {
    category: 'masonry',
    material: 'Common Bricks',
    description: 'Fired clay brick — partition walls',
    unit: '1000 pieces',
    price_kes: 9500,
    region: 'mombasa',
    supplier: 'East Africa Bricks',
    supplier_contact: '+254 722 111 222',
  },
  {
    category: 'roofing',
    material: 'Mabati Box Profile 0.3mm',
    description: 'Gauge 30 — budget roofing',
    unit: 'm²',
    price_kes: 550,
    region: 'mombasa',
    supplier: 'Mabati Rolling Mills',
    supplier_contact: '+254 700 622 284',
  },
  {
    category: 'roofing',
    material: 'Mabati Box Profile 0.4mm',
    description: 'Gauge 28 — standard residential roofing',
    unit: 'm²',
    price_kes: 750,
    region: 'mombasa',
    supplier: 'Mabati Rolling Mills',
    supplier_contact: '+254 700 622 284',
  },
  {
    category: 'roofing',
    material: 'Decra Stone Coated Tile',
    description: 'Premium roofing tile — 50yr warranty',
    unit: 'm²',
    price_kes: 2200,
    region: 'mombasa',
    supplier: 'Decra Kenya',
    supplier_contact: '+254 722 332 272',
  },
  {
    category: 'roofing',
    material: 'Clay Roof Tile',
    description: 'Traditional terracotta — coastal aesthetic',
    unit: 'piece',
    price_kes: 55,
    region: 'mombasa',
    supplier: 'Coast Tiles Ltd',
    supplier_contact: '+254 722 334 455',
  },
  {
    category: 'roofing',
    material: 'Roofing Timber 2x4',
    description: 'Cypress rafters — roof structure',
    unit: 'lm',
    price_kes: 180,
    region: 'mombasa',
    supplier: 'Coast Timber Mart',
    supplier_contact: '+254 722 556 677',
  },
  {
    category: 'roofing',
    material: 'Roofing Timber 2x6',
    description: 'Cypress purlins — longer spans',
    unit: 'lm',
    price_kes: 280,
    region: 'mombasa',
    supplier: 'Coast Timber Mart',
    supplier_contact: '+254 722 556 677',
  },
  {
    category: 'roofing',
    material: 'Roofing Nails 3 inch',
    description: 'Galvanised — for iron sheets',
    unit: 'kg',
    price_kes: 200,
    region: 'mombasa',
    supplier: 'Coast Builders Centre',
    supplier_contact: '+254 41 231 0000',
  },
  {
    category: 'timber',
    material: 'Timber 2x2 Cypress',
    description: 'Framing, furring strips',
    unit: 'lm',
    price_kes: 80,
    region: 'mombasa',
    supplier: 'Coast Timber Mart',
    supplier_contact: '+254 722 556 677',
  },
  {
    category: 'timber',
    material: 'Timber 2x3 Cypress',
    description: 'Formwork, partitions',
    unit: 'lm',
    price_kes: 120,
    region: 'mombasa',
    supplier: 'Coast Timber Mart',
    supplier_contact: '+254 722 556 677',
  },
  {
    category: 'timber',
    material: 'Plywood 18mm',
    description: 'Structural formwork sheets',
    unit: 'sheet',
    price_kes: 2800,
    region: 'mombasa',
    supplier: 'Coast Timber Mart',
    supplier_contact: '+254 722 556 677',
  },
  {
    category: 'timber',
    material: 'Plywood 12mm',
    description: 'General formwork and joinery',
    unit: 'sheet',
    price_kes: 2200,
    region: 'mombasa',
    supplier: 'Coast Timber Mart',
    supplier_contact: '+254 722 556 677',
  },
  {
    category: 'finishes',
    material: 'Ceramic Floor Tile 30x30',
    description: 'Budget grade — utility areas',
    unit: 'm²',
    price_kes: 900,
    region: 'mombasa',
    supplier: 'Tile & Carpet Centre',
    supplier_contact: '+254 41 222 5000',
  },
  {
    category: 'finishes',
    material: 'Ceramic Floor Tile 60x60',
    description: 'Mid-range — living areas',
    unit: 'm²',
    price_kes: 2000,
    region: 'mombasa',
    supplier: 'Tile & Carpet Centre',
    supplier_contact: '+254 41 222 5000',
  },
  {
    category: 'finishes',
    material: 'Porcelain Floor Tile 60x60',
    description: 'Premium — bedrooms, offices',
    unit: 'm²',
    price_kes: 3500,
    region: 'mombasa',
    supplier: 'Tile & Carpet Centre',
    supplier_contact: '+254 41 222 5000',
  },
  {
    category: 'finishes',
    material: 'Wall Tile 30x45',
    description: 'Ceramic — bathrooms, kitchens',
    unit: 'm²',
    price_kes: 1200,
    region: 'mombasa',
    supplier: 'Tile & Carpet Centre',
    supplier_contact: '+254 41 222 5000',
  },
  {
    category: 'finishes',
    material: 'Crown Paint Internal — 20L',
    description: 'Matt emulsion — interior walls',
    unit: '20L tin',
    price_kes: 5200,
    region: 'mombasa',
    supplier: 'Crown Paints Kenya',
    supplier_contact: '+254 722 204 888',
  },
  {
    category: 'finishes',
    material: 'Crown Paint External — 20L',
    description: 'Weather Shield — exterior walls',
    unit: '20L tin',
    price_kes: 6800,
    region: 'mombasa',
    supplier: 'Crown Paints Kenya',
    supplier_contact: '+254 722 204 888',
  },
  {
    category: 'finishes',
    material: 'Cement Plaster',
    description: '1:4 mix — wall plastering per sqm',
    unit: 'm²',
    price_kes: 350,
    region: 'mombasa',
    supplier: 'Labour included',
    supplier_contact: '',
  },
  {
    category: 'plumbing',
    material: 'uPVC Pipe 110mm',
    description: 'Soil and waste — main stack',
    unit: 'm',
    price_kes: 480,
    region: 'mombasa',
    supplier: 'Plumb Master Mombasa',
    supplier_contact: '+254 722 888 999',
  },
  {
    category: 'plumbing',
    material: 'uPVC Pipe 50mm',
    description: 'Branch waste pipes — basins, showers',
    unit: 'm',
    price_kes: 220,
    region: 'mombasa',
    supplier: 'Plumb Master Mombasa',
    supplier_contact: '+254 722 888 999',
  },
  {
    category: 'plumbing',
    material: 'PPR Pipe 20mm',
    description: 'Cold water supply',
    unit: 'm',
    price_kes: 180,
    region: 'mombasa',
    supplier: 'Plumb Master Mombasa',
    supplier_contact: '+254 722 888 999',
  },
  {
    category: 'plumbing',
    material: 'PPR Pipe 25mm',
    description: 'Hot water supply — solar systems',
    unit: 'm',
    price_kes: 250,
    region: 'mombasa',
    supplier: 'Plumb Master Mombasa',
    supplier_contact: '+254 722 888 999',
  },
  {
    category: 'plumbing',
    material: 'WC Suite Complete',
    description: 'Close-coupled toilet — budget',
    unit: 'set',
    price_kes: 8500,
    region: 'mombasa',
    supplier: 'Sanitary World Mombasa',
    supplier_contact: '+254 41 222 3333',
  },
  {
    category: 'plumbing',
    material: 'Basin Complete',
    description: 'Ceramic washbasin with taps — budget',
    unit: 'set',
    price_kes: 5500,
    region: 'mombasa',
    supplier: 'Sanitary World Mombasa',
    supplier_contact: '+254 41 222 3333',
  },
  {
    category: 'plumbing',
    material: 'Shower Tray + Fittings',
    description: 'Acrylic tray with mixer — budget',
    unit: 'set',
    price_kes: 12000,
    region: 'mombasa',
    supplier: 'Sanitary World Mombasa',
    supplier_contact: '+254 41 222 3333',
  },
  {
    category: 'plumbing',
    material: '500L Water Tank',
    description: 'Kentank polyethylene — rooftop',
    unit: 'piece',
    price_kes: 9500,
    region: 'mombasa',
    supplier: 'Kentank',
    supplier_contact: '+254 722 536 825',
  },
  {
    category: 'plumbing',
    material: 'Plumbing Point — Complete',
    description: 'Full installation per wet point',
    unit: 'point',
    price_kes: 14000,
    region: 'mombasa',
    supplier: 'Labour + materials',
    supplier_contact: '',
  },
  {
    category: 'electrical',
    material: '2.5mm² Twin & Earth Cable',
    description: 'Power circuits — sockets',
    unit: 'm',
    price_kes: 95,
    region: 'mombasa',
    supplier: 'Elec Masters Mombasa',
    supplier_contact: '+254 722 444 555',
  },
  {
    category: 'electrical',
    material: '1.5mm² Twin & Earth Cable',
    description: 'Lighting circuits',
    unit: 'm',
    price_kes: 65,
    region: 'mombasa',
    supplier: 'Elec Masters Mombasa',
    supplier_contact: '+254 722 444 555',
  },
  {
    category: 'electrical',
    material: '6mm² Single Core Cable',
    description: 'Cooker, geyser circuits',
    unit: 'm',
    price_kes: 180,
    region: 'mombasa',
    supplier: 'Elec Masters Mombasa',
    supplier_contact: '+254 722 444 555',
  },
  {
    category: 'electrical',
    material: 'DB Board 12-way',
    description: 'Consumer unit with MCBs',
    unit: 'piece',
    price_kes: 8500,
    region: 'mombasa',
    supplier: 'Elec Masters Mombasa',
    supplier_contact: '+254 722 444 555',
  },
  {
    category: 'electrical',
    material: 'Single Socket Outlet',
    description: 'MK brand — 13A switched',
    unit: 'piece',
    price_kes: 380,
    region: 'mombasa',
    supplier: 'Elec Masters Mombasa',
    supplier_contact: '+254 722 444 555',
  },
  {
    category: 'electrical',
    material: 'Double Socket Outlet',
    description: 'MK brand — 13A switched',
    unit: 'piece',
    price_kes: 520,
    region: 'mombasa',
    supplier: 'Elec Masters Mombasa',
    supplier_contact: '+254 722 444 555',
  },
  {
    category: 'electrical',
    material: 'Electrical Point — Complete',
    description: 'Full installation per point',
    unit: 'point',
    price_kes: 9500,
    region: 'mombasa',
    supplier: 'Labour + materials',
    supplier_contact: '',
  },
  {
    category: 'doors_windows',
    material: 'Flush Door — Solid Core',
    description: '900x2100mm — internal doors',
    unit: 'piece',
    price_kes: 8500,
    region: 'mombasa',
    supplier: 'Coast Doors & Windows',
    supplier_contact: '+254 722 667 788',
  },
  {
    category: 'doors_windows',
    material: 'Steel Security Door',
    description: 'Main entrance — with 3-point lock',
    unit: 'piece',
    price_kes: 28000,
    region: 'mombasa',
    supplier: 'Steel Shield Kenya',
    supplier_contact: '+254 722 999 000',
  },
  {
    category: 'doors_windows',
    material: 'Aluminium Casement Window',
    description: '1200x1200mm — standard residential',
    unit: 'piece',
    price_kes: 12000,
    region: 'mombasa',
    supplier: 'Coast Aluminium Works',
    supplier_contact: '+254 41 222 7777',
  },
  {
    category: 'doors_windows',
    material: 'Aluminium Sliding Door',
    description: '2100x2100mm — patio/balcony',
    unit: 'piece',
    price_kes: 35000,
    region: 'mombasa',
    supplier: 'Coast Aluminium Works',
    supplier_contact: '+254 41 222 7777',
  },
  {
    category: 'labour',
    material: 'Skilled Mason',
    description: 'Daily rate — bricklaying, plastering',
    unit: 'day',
    price_kes: 1200,
    region: 'mombasa',
    supplier: 'Market rate',
    supplier_contact: '',
  },
  {
    category: 'labour',
    material: 'General Labourer',
    description: 'Daily rate — mixing, carrying',
    unit: 'day',
    price_kes: 700,
    region: 'mombasa',
    supplier: 'Market rate',
    supplier_contact: '',
  },
  {
    category: 'labour',
    material: 'Carpenter',
    description: 'Daily rate — formwork, roofing',
    unit: 'day',
    price_kes: 1400,
    region: 'mombasa',
    supplier: 'Market rate',
    supplier_contact: '',
  },
  {
    category: 'labour',
    material: 'Electrician',
    description: 'Daily rate — first fix and second fix',
    unit: 'day',
    price_kes: 2000,
    region: 'mombasa',
    supplier: 'Market rate',
    supplier_contact: '',
  },
  {
    category: 'labour',
    material: 'Plumber',
    description: 'Daily rate — pipe work and fittings',
    unit: 'day',
    price_kes: 1800,
    region: 'mombasa',
    supplier: 'Market rate',
    supplier_contact: '',
  },
  {
    category: 'labour',
    material: 'Tile Fixer',
    description: 'Daily rate — floor and wall tiling',
    unit: 'day',
    price_kes: 1500,
    region: 'mombasa',
    supplier: 'Market rate',
    supplier_contact: '',
  },
  {
    category: 'labour',
    material: 'Painter',
    description: 'Daily rate — interior and exterior',
    unit: 'day',
    price_kes: 1200,
    region: 'mombasa',
    supplier: 'Market rate',
    supplier_contact: '',
  },
  {
    category: 'labour',
    material: 'Structural Engineer Site Visit',
    description: 'Per visit supervision fee',
    unit: 'visit',
    price_kes: 15000,
    region: 'mombasa',
    supplier: 'IEK registered engineer',
    supplier_contact: '',
  },
]

export async function seedMaterialPrices() {
  console.log('🌱 Seeding Mombasa material prices...')

  const { data, error } = await supabase
    .from('material_prices')
    .upsert(MOMBASA_PRICES, {
      onConflict: 'material,region',
      ignoreDuplicates: false,
    })

  if (error) {
    console.error('❌ Seed failed:', error)
    throw error
  }

  console.log(`✅ Seeded ${MOMBASA_PRICES.length} material prices for Mombasa`)
  return data
}

seedMaterialPrices()
  .then(() => {
    console.log('🎉 Seed completed successfully')
    process.exit(0)
  })
  .catch((error) => {
    console.error('💥 Seed failed:', error)
    process.exit(1)
  })
